version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum update -y
      - yum install -y git

  build:
    commands:
      - echo "Fetching the latest uploaded image..."
      - LAST_IMAGE=$(aws s3 ls s3://imageupload259/ --recursive | sort | tail -n 1 | awk '{print $4}')
      - echo "Latest uploaded image:$LAST_IMAGE"

      - if [[ -z "$LAST_IMAGE" ]]; then echo "No image found. Exiting..."; exit 1; fi

      - git clone https://"$GITHUB_TOKEN"@github.com/Esha259/AWS-Image-CI-CD.git repo
      - cd repo

      - sed -i "s|<title>.*</title>|<title>${LAST_IMAGE}</title>|g" index.html
      - echo "Updated title in index.html"

      # Configure Git
      - git config --global user.email "eshagandhi22@gmail.com"
      - git config --global user.name "Esha259"

      # Set correct remote URL for authentication
      - git remote set-url origin "https://Esha259:$GITHUB_TOKEN@github.com/AWS-Image-CI-CD.git"
      - git remote -v

      - git add index.html
      - git commit -m "Updated title with latest image:${LAST_IMAGE}" || echo "No changes to commit"

      # Push the changes
      - git push origin main || echo "Push failed"

artifacts:
  files:
    - '**/*'
